### ISSUE TITLE
The problem when building the project.

### ISSUE THREAD

**Issue by Yuttoh** [HybrisMC/Core#1]
Hello, so I'm having a build problem, which keeps showing this in the cmd. If you can help me or fix the bug, I would appreciate it.
![image](https://github.com/HybrisMC/Core/assets/98183285/898b1c58-4bff-4d46-afa6-0f41d9d12cc1)

**Comment by Yuttoh** [comment]
Another Problem: 

gradle build
Starting a Gradle Daemon, 2 incompatible and 2 stopped Daemons could not be reused, use --status for details

> Configure project :1.12
Downloading game JAR for deobfuscation environment

> Configure project :1.16.1
Downloading game JAR for deobfuscation environment

> Configure project :1.19.4
Downloading game JAR for deobfuscation environment

> Configure project :1.20
Downloading game JAR for deobfuscation environment

> Configure project :1.8
Downloading game JAR for deobfuscation environment

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':core:compileJava'.
> Could not resolve all task dependencies for configuration ':core:compileClasspath'.
   > Could not resolve com.grappenmaker:nasty-jvm-util.
     Required by:
         project :core
      > No matching configuration of project :class-util was found. The consumer was configured to find a library for use during compile-time, compatible with Java 16, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
          - None of the consumable configurations have attributes.

**Comment by betterclient** [comment]
clear the class-util folder than do "git submodule update --init"

**Comment by Yuttoh** [comment]
Thanks!

**Comment by 770grappenmaker** [comment]
> clear the class-util folder than do "git submodule update --init"

You should not have to clear the folder tho
